In [1]:
#%pip install torch torchvision torchaudio

In [10]:
import torch

In [11]:
torch.cuda.is_available()

True

In [12]:
a = torch.rand(1,10)

In [13]:
a

tensor([[0.8272, 0.2934, 0.7986, 0.6793, 0.1181, 0.6438, 0.2988, 0.8412, 0.0658,
         0.5405]])

In [14]:
a=[]
for i in range(10):
    a.append(torch.rand(1,10))

In [16]:
print(len(a))
print(a[0].shape)

10
torch.Size([1, 10])


In [17]:
b = torch.Tensor(len(a), a[0].shape[0], a[0].shape[1])
torch.cat(a, out=b)

/tmp/ipykernel_14221/634085534.py:2: UserWarning: An output with one or more elements was resized since it had shape [10, 1, 10], which does not match the required output shape [10, 10]. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at ../aten/src/ATen/native/Resize.cpp:28.)
  torch.cat(a, out=b)


tensor([[0.3109, 0.8887, 0.6243, 0.5740, 0.1396, 0.8681, 0.2467, 0.9656, 0.5947,
         0.4324],
        [0.9523, 0.8173, 0.8701, 0.8126, 0.9067, 0.9285, 0.8916, 0.9214, 0.1100,
         0.9049],
        [0.3982, 0.1417, 0.8455, 0.0188, 0.8599, 0.1110, 0.0134, 0.3134, 0.2477,
         0.5553],
        [0.5704, 0.0742, 0.7791, 0.3132, 0.5750, 0.3035, 0.0089, 0.2052, 0.9976,
         0.4892],
        [0.6090, 0.0375, 0.0824, 0.7937, 0.6914, 0.4407, 0.3626, 0.5142, 0.1409,
         0.8135],
        [0.8760, 0.8489, 0.2023, 0.2099, 0.7765, 0.5352, 0.6632, 0.0013, 0.6420,
         0.2334],
        [0.4389, 0.1489, 0.6542, 0.9040, 0.8807, 0.0500, 0.0294, 0.8357, 0.6210,
         0.6719],
        [0.6261, 0.1185, 0.8343, 0.0114, 0.1974, 0.8012, 0.8484, 0.9134, 0.3226,
         0.8730],
        [0.7221, 0.5021, 0.6461, 0.8591, 0.3493, 0.2955, 0.8053, 0.1423, 0.0052,
         0.1828],
        [0.5828, 0.6128, 0.1686, 0.7622, 0.9288, 0.0861, 0.9700, 0.5576, 0.7677,
         0.4405]])

In [19]:
b.shape

torch.Size([10, 10])

In [20]:
torch.save(b, 'tensor.pt')

In [22]:
c=torch.load('tensor.pt')

In [23]:
c

tensor([[0.3109, 0.8887, 0.6243, 0.5740, 0.1396, 0.8681, 0.2467, 0.9656, 0.5947,
         0.4324],
        [0.9523, 0.8173, 0.8701, 0.8126, 0.9067, 0.9285, 0.8916, 0.9214, 0.1100,
         0.9049],
        [0.3982, 0.1417, 0.8455, 0.0188, 0.8599, 0.1110, 0.0134, 0.3134, 0.2477,
         0.5553],
        [0.5704, 0.0742, 0.7791, 0.3132, 0.5750, 0.3035, 0.0089, 0.2052, 0.9976,
         0.4892],
        [0.6090, 0.0375, 0.0824, 0.7937, 0.6914, 0.4407, 0.3626, 0.5142, 0.1409,
         0.8135],
        [0.8760, 0.8489, 0.2023, 0.2099, 0.7765, 0.5352, 0.6632, 0.0013, 0.6420,
         0.2334],
        [0.4389, 0.1489, 0.6542, 0.9040, 0.8807, 0.0500, 0.0294, 0.8357, 0.6210,
         0.6719],
        [0.6261, 0.1185, 0.8343, 0.0114, 0.1974, 0.8012, 0.8484, 0.9134, 0.3226,
         0.8730],
        [0.7221, 0.5021, 0.6461, 0.8591, 0.3493, 0.2955, 0.8053, 0.1423, 0.0052,
         0.1828],
        [0.5828, 0.6128, 0.1686, 0.7622, 0.9288, 0.0861, 0.9700, 0.5576, 0.7677,
         0.4405]])

In [24]:
for element in c:
    print(element)

tensor([0.3109, 0.8887, 0.6243, 0.5740, 0.1396, 0.8681, 0.2467, 0.9656, 0.5947,
        0.4324])
tensor([0.9523, 0.8173, 0.8701, 0.8126, 0.9067, 0.9285, 0.8916, 0.9214, 0.1100,
        0.9049])
tensor([0.3982, 0.1417, 0.8455, 0.0188, 0.8599, 0.1110, 0.0134, 0.3134, 0.2477,
        0.5553])
tensor([0.5704, 0.0742, 0.7791, 0.3132, 0.5750, 0.3035, 0.0089, 0.2052, 0.9976,
        0.4892])
tensor([0.6090, 0.0375, 0.0824, 0.7937, 0.6914, 0.4407, 0.3626, 0.5142, 0.1409,
        0.8135])
tensor([0.8760, 0.8489, 0.2023, 0.2099, 0.7765, 0.5352, 0.6632, 0.0013, 0.6420,
        0.2334])
tensor([0.4389, 0.1489, 0.6542, 0.9040, 0.8807, 0.0500, 0.0294, 0.8357, 0.6210,
        0.6719])
tensor([0.6261, 0.1185, 0.8343, 0.0114, 0.1974, 0.8012, 0.8484, 0.9134, 0.3226,
        0.8730])
tensor([0.7221, 0.5021, 0.6461, 0.8591, 0.3493, 0.2955, 0.8053, 0.1423, 0.0052,
        0.1828])
tensor([0.5828, 0.6128, 0.1686, 0.7622, 0.9288, 0.0861, 0.9700, 0.5576, 0.7677,
        0.4405])
